### ISSUE TITLE
El boton ">>" no intenta generar nuevas instancias

### ISSUE THREAD

**Issue by ramirofd** [castrosoft/IngSoft-2016-SoftDuino#1]
Logre hacer que muestre la información, pero no encuentro como hacer funcionar lo de generar nuevas instancias con el boton ">>"

**Comment by castrosoft** [comment]
Se corrigió el funcionamiento del botón >> modificando el método increaseBPM() de HeartController para que este intente generar nuevas instancias del modelo.
